# Generated by Django 3.2.8 on 2021-10-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, max_length=100, verbose_name='Channel Name')),
                ('country', models.CharField(db_index=True, max_length=2, verbose_name='Country Name')),
                ('faced_date', models.DateField(db_index=True, verbose_name='Faced Date')),
                ('os', models.CharField(db_index=True, max_length=100, verbose_name='Operation System Name')),
                ('impressions', models.IntegerField(verbose_name='Impressions count')),
                ('clicks', models.IntegerField(verbose_name='Click count')),
                ('installs', models.IntegerField(verbose_name='Installs count')),
                ('spend', models.FloatField(verbose_name='Spend Count')),
                ('revenue', models.FloatField(verbose_name='Revenue Count')),
            ],
        ),
    ]
